exec nohup pactl set-sink-volume @DEFAULT_SINK@ 50%
exec nohup pactl set-source-volume @DEFAULT_SOURCE@ 25% 
exec awww-daemon &
exec xwayland-satellite &
exec nohup foot &> /dev/null
exec nohup firefox &> /dev/null
exec nohup brave &> /dev/null
exec flatpak run com.github.wwmm.easyeffects &
# exec kitten panel --edge=background --margin-left 1200 -o background_opacity=0.2 -o background=black btop &
