floating_minimum_size 1240 x 900

assign {
    [app_id="foot"]                               workspace number 1
    [app_id="firefox"]                            workspace number 2
    [app_id="brave-browser"]                      workspace number 3
    [app_id="com.obsproject.Studio"]              workspace number 4
    [app_id="org.pipewire.Helvum"]                workspace number 4
    [app_id="org.kde.easyeffects"]                workspace number 4
    [class="discord"]                             workspace number 5
    [class="gimp"]                                workspace number 6
}

for_window {
    [app_id="com.obsproject.Studio"]              opacity set 0.9
    [app_id="org.pipewire.Helvum"]                opacity set 0.9
    [app_id="com.github.wwmm.easyeffects"]        opacity set 0.9
    [app_id="firefox"]                            opacity set 0.98
    [app_id="brave-browser"]                      opacity set 0.98
}

title_align center

workspace 1 gaps outer 2
workspace 1 gaps inner 2

workspace 5 gaps outer 60
workspace 5 gaps inner 20

# define display output names
# set $disp1 "eDP-1"
# set $disp2 "HDMI-A-1"

# default display outputs for workspaces with fallback to disp1
# workspace 1 output $disp1
# workspace 2 output $disp2 $disp1
# workspace 3 output $disp2 $disp1
# workspace 4 output $disp2 $disp1
# workspace 5 output $disp2 $disp1
# workspace 6 output $disp2 $disp1
# workspace 7 output $disp2 $disp1
# workspace 8 output $disp2 $disp1
# workspace 9 output $disp1
# workspace 10 output $disp1
